apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  source:
    repoURL: us-docker.pkg.dev/solo-public/kagent-enterprise-helm/charts
    chart: kagent-enterprise-crds
    targetRevision: 0.4.3
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true, ServerSideApply=true ]