apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: agentgateway-system
  source:
    repoURL: us-docker.pkg.dev/solo-public/enterprise-agentgateway/charts
    chart: enterprise-agentgateway
    targetRevision: {{ .Values.agw.version }}
    helm:
      values: |
        licensing:
          createSecret: false
          secretName: enterprise-agentgateway-license
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true ]
