apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agw-ui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: agentgateway-system
  source:
    repoURL: us-docker.pkg.dev/solo-public/solo-enterprise-helm/charts
    chart: management
    targetRevision: {{ index .Values "agw-ui" "version" }}
    helm:
      values: |
        management-crds:
          enabled: false
        licensing:
          licenseSecretRef:
            name: enterprise-agentgateway-license
            namespace: agentgateway-system
        global:
          imagePullPolicy: IfNotPresent
          imagePullSecrets: []
        service:
          type: ClusterIP
          clusterIP: ""
        products:
          kagent:
            enabled: true
            namespace: kagent
          agentgateway:
            enabled: true
            namespace: agentgateway-system
          mesh:
            enabled: false
          agentregistry:
            enabled: true
        clickhouse:
          enabled: true
        tracing:
          verbose: true
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true ]
