apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agw-ui-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: agentgateway-system
  source:
    repoURL: us-docker.pkg.dev/solo-public/solo-enterprise-helm/charts
    chart: management-crds
    targetRevision: {{ index .Values "agw-ui" "version" }}
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true, ServerSideApply=true ]
