apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: {{ .Values.grafanaPrometheus.version }}
    helm:
      values: |
        alertmanager:
          enabled: false
        grafana:
          adminPassword: {{ .Values.grafanaPrometheus.grafanaAdminPassword }}
          service:
            type: ClusterIP
            port: 3000
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"
              searchNamespace: monitoring
        nodeExporter:
          enabled: false
        prometheus:
          service:
            type: ClusterIP
          prometheusSpec:
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true, ServerSideApply=true ]
