apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  source:
    repoURL: us-docker.pkg.dev/solo-public/kagent-enterprise-helm/charts
    chart: kagent-enterprise
    targetRevision: {{ .Values.kagent.version }}
    helm:
      values: |
        licensing:
          createSecret: false
          secretName: enterprise-kagent-license
        providers:
          default: openAI
          openAI:
            apiKeySecretRef: kagent-openai
        otel:
          tracing:
            enabled: true
            exporter:
              otlp:
                endpoint: solo-enterprise-telemetry-collector.solo-enterprise.svc.cluster.local:4317
                insecure: true
        oidc:
          issuer: http://solo-enterprise-ui.solo-enterprise.svc.cluster.local:5556
        argo-rollouts-agent:
          enabled: true
        cilium-debug-agent:
          enabled: true
        cilium-manager-agent:
          enabled: true
        cilium-policy-agent:
          enabled: true
        helm-agent:
          enabled: true
        istio-agent:
          enabled: true
        k8s-agent:
          enabled: true
        kgateway-agent:
          enabled: true
        observability-agent:
          enabled: true
        promql-agent:
          enabled: true
        # Tool server dependencies
        grafana-mcp:
          enabled: true
        kagent-tools:
          enabled: true
        querydoc:
          enabled: true
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true ]
